### ISSUE TITLE
The etcd charm requires Juju version > 1.22, as it uses "is_leader"

### ISSUE THREAD

**Issue by mbruzek** [whitmo/etcd-charm#15]
Neil Wilson reported that they tried to use the kubernetes charms on the Juju that installs with Ubuntu and was not able to run the etcd charm.

We should attempt to fix this problem and if we can not, document that as a limitation in the Kubernetes work and in the etcd readme file.

Thanks to Neil Wilson for reporting this problem!

**Comment by marcoceppi** [comment]
It seems #16 resolves this issue, can you confirm?
